'use client';
import {useState,useRef} from 'react';
import Image from 'next/image';
import {Modal} from './modal';
import {Icon} from './icon';
export type Choice={value:string;label:string;detail?:string;image?:string};
export function ChoicePanel({label,value,options,onChange,disabled=false}:{label:string;value:string;options:Choice[];onChange:(value:string)=>void;disabled?:boolean}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState('');const list=useRef<HTMLDivElement>(null);
 const selected=options.find(o=>o.value===value),filtered=options.filter(o=>`${o.label} ${o.detail??''}`.toLocaleLowerCase('ru').includes(query.toLocaleLowerCase('ru')));
 function step(key:string){const buttons=[...list.current?.querySelectorAll<HTMLButtonElement>('button')??[]];if(!buttons.length)return;const i=buttons.indexOf(document.activeElement as HTMLButtonElement);const next=key==='Home'?0:key==='End'?buttons.length-1:key==='ArrowUp'?Math.max(0,i-1):Math.min(buttons.length-1,i+1);buttons[next]?.focus();}
 return <><button type="button" className="choice-trigger" aria-label={`${label}: ${selected?.label??'Выбрать'}`} aria-haspopup="dialog" disabled={disabled} onClick={()=>{setQuery('');setOpen(true);}}><span><small>{label}</small><strong>{selected?.label??'Выбрать'}</strong></span><Icon name="chevron" size={17}/></button>{open&&<Modal title={label} wide={options.some(o=>o.image)} onClose={()=>setOpen(false)}><div className="choice-panel"><span className="micro-label">CHIPS / ВЫБОР</span><h2>{label}</h2>{options.length>5&&<label className="search-input"><Icon name="search" size={18}/><input aria-label={`Поиск: ${label}`} placeholder="Название или покрытие" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();step(e.key);}}}/></label>}<p className="choice-count" role="status">Найдено: {filtered.length}</p><div ref={list} className={`choice-options ${options.some(o=>o.image)?'with-images':''}`} onKeyDown={e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();step(e.key);}}}>{filtered.map(o=><button type="button" key={o.value} aria-pressed={value===o.value} onClick={()=>{onChange(o.value);setOpen(false);}}>{o.image&&<Image src={o.image} alt="" width={240} height={160}/>}<span><strong>{o.label}</strong>{o.detail&&<small>{o.detail}</small>}</span><span className="choice-check" aria-hidden="true">{value===o.value?'✓':'↗'}</span></button>)}</div>{!filtered.length&&<p className="choice-empty">Ничего не найдено. Попробуйте другое название.</p>}</div></Modal>}</>;
}
