'use client';
import {useState,type CSSProperties} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import type {Product} from '@/lib/types';
import {chipsToRub,formatMinor} from '@/lib/money';
import {Price} from './price';
import {ChoicePanel} from './choice-panel';
export function SkinCompare({products}:{products:Product[]}){
 const weapons=[...new Set(products.map(p=>p.weapon))].filter(w=>products.filter(p=>p.weapon===w).length>1);
 const [weapon,setWeapon]=useState(weapons.includes('AK-47')?'AK-47':weapons[0]??''),[ids,setIds]=useState<[string,string]>(['','']),[split,setSplit]=useState(50);
 const pool=products.filter(p=>p.weapon===weapon),left=pool.find(p=>p.id===ids[0])??pool[0],right=pool.find(p=>p.id===ids[1]&&p.id!==left?.id)??pool.find(p=>p.id!==left?.id);
 if(!left||!right)return null;const pair=[left,right],difference=Math.abs(left.priceMinor-right.priceMinor),cheaper=left.priceMinor<right.priceMinor?left:right;
 function select(index:number,id:string){const other=pair[1-index],alternate=other.id===id?pair[index].id:other.id;setIds(index===0?[id,alternate]:[alternate,id]);}
 return <section className="section compare-lab" id="compare" aria-labelledby="compare-title"><div className="chapter-heading"><span className="micro-label">02 / СРАВНЕНИЕ</span><h2 id="compare-title">Один силуэт.<br/><em>Два характера.</em></h2><p>Сдвинь границу, чтобы рассмотреть оба покрытия.</p></div><div className="compare-instrument"><div className="compare-command"><ChoicePanel label="Оружие" value={weapon} options={weapons.map(w=>({value:w,label:w}))} onChange={w=>{setWeapon(w);setIds(['','']);}}/><span className="micro-label">A / B · СКИНЫ CS2</span></div><div className="compare-canvas" style={{'--split':`${split}%`} as CSSProperties}><span className="compare-letter letter-a" aria-hidden="true">A</span><span className="compare-letter letter-b" aria-hidden="true">B</span><div className="compare-layer compare-right"><Image src={right.imageUrl} alt={`B: ${right.name}`} width={1000} height={600}/></div><div className="compare-layer compare-left"><Image src={left.imageUrl} alt={`A: ${left.name}`} width={1000} height={600}/></div><span className="compare-divider" aria-hidden="true"><b>↔</b></span><input className="compare-range" type="range" min="0" max="100" value={split} aria-label="Граница сравнения" aria-valuetext={`${split}% покрытия A`} onChange={e=>setSplit(Number(e.target.value))}/><span className="compare-hint">Двигай границу ↔</span></div><div className="compare-pickers">{pair.map((p,i)=><ChoicePanel key={i} label={i===0?'Покрытие A':'Покрытие B'} value={p.id} options={pool.map(p=>({value:p.id,label:p.finish,detail:p.condition,image:p.imageUrl}))} onChange={id=>select(i,id)}/>)}</div><div className="compare-readout">{pair.map((p,i)=><article key={p.id}><div className="readout-name"><b>{i===0?'A':'B'}</b><h3>{p.finish}</h3><Link href={`/catalog/${p.id}`} aria-label={`Открыть ${p.name}`}>↗</Link></div><Price minor={p.priceMinor}/><div className="measure-track"><span style={{width:`${p.priceMinor/Math.max(left.priceMinor,right.priceMinor)*100}%`}}/></div><dl><div><dt>Float</dt><dd>{p.float?.toFixed(6)??'—'}</dd></div><div><dt>Износ</dt><dd>{p.condition}</dd></div><div><dt>StatTrak™</dt><dd>{p.stattrak?'Есть':'Нет'}</dd></div></dl></article>)}</div><div className="compare-delta" role="status">{difference?<><span>{cheaper.finish} дешевле на</span><strong>{formatMinor(Math.abs(chipsToRub(left.priceMinor)-chipsToRub(right.priceMinor)))} <small>₽</small></strong></>:<span>Одинаковая стоимость</span>}<p>Float описывает износ.<br/>Цена зависит и от других свойств.</p></div></div></section>;
}
